<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pemesanan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get pemesanan by id_pemesanan
     */
    function get_pemesanan($id_pemesanan)
    {
        return $this->db->get_where('pemesanan',array('id_pemesanan'=>$id_pemesanan))->row_array();
    }
    
    /*
     * Get all pemesanans count
     */
    function get_all_pemesanans_count()
    {
        $this->db->from('pemesanan');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all pemesanans
     */
    function get_all_pemesanans($params = array())
    {
        $this->db->order_by('id_pemesanan', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('pemesanan')->result_array();
    }
        
    /*
     * function to add new pemesanan
     */
    function add_pemesanan($params)
    {
        $this->db->insert('pemesanan',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update pemesanan
     */
    function update_pemesanan($id_pemesanan,$params)
    {
        $this->db->where('id_pemesanan',$id_pemesanan);
        return $this->db->update('pemesanan',$params);
    }
    
    /*
     * function to delete pemesanan
     */
    function delete_pemesanan($id_pemesanan)
    {
        return $this->db->delete('pemesanan',array('id_pemesanan'=>$id_pemesanan));
    }
}
